/**
 * Kenya's administrative hierarchy: county -> sub-county (constituency) -> ward.
 *
 * Codes are hierarchical and dot-separated, so any level can be derived from a ward code without a
 * lookup: `machakos.mavoko.athi-river` belongs to `machakos.mavoko`, which belongs to `machakos`.
 * The dataset itself is generated by scripts/build-kenya-data.mjs from GADM 4.1.
 */

export type LocationLevel = "kenya" | "county" | "sub-county" | "ward";

export type WardRef = {
  code: string;
  name: string;
};

export type SubCountyRef = {
  code: string;
  name: string;
  wards: WardRef[];
};

export type CountyRef = {
  code: string;
  name: string;
  subCounties: SubCountyRef[];
};

export type KenyaHierarchy = {
  source: string;
  generatedAt: string;
  counties: CountyRef[];
};

/** A point in the drill-down. Every field below the current level is undefined. */
export type LocationSelection = {
  countyCode?: string;
  subCountyCode?: string;
  wardCode?: string;
};

export type ResolvedLocation = {
  level: LocationLevel;
  county?: CountyRef;
  subCounty?: SubCountyRef;
  ward?: WardRef;
};

export const FINANCIAL_YEARS = ["2025/2026", "2024/2025", "2023/2024", "2022/2023"];

export const KENYA_DATA_SOURCE = "GADM 4.1 — Database of Global Administrative Areas";

export function countyCodeOf(code: string | undefined): string | undefined {
  return code?.split(".")[0] || undefined;
}

export function subCountyCodeOf(code: string | undefined): string | undefined {
  if (!code) return undefined;
  const parts = code.split(".");
  return parts.length >= 2 ? `${parts[0]}.${parts[1]}` : undefined;
}

export function levelOf(selection: LocationSelection): LocationLevel {
  if (selection.wardCode) return "ward";
  if (selection.subCountyCode) return "sub-county";
  if (selection.countyCode) return "county";
  return "kenya";
}

export function findCounty(hierarchy: KenyaHierarchy | null, code: string | undefined) {
  if (!hierarchy || !code) return undefined;
  const county = countyCodeOf(code);
  return hierarchy.counties.find((item) => item.code === county);
}

export function findSubCounty(hierarchy: KenyaHierarchy | null, code: string | undefined) {
  if (!code) return undefined;
  const county = findCounty(hierarchy, code);
  const subCounty = subCountyCodeOf(code);
  return county?.subCounties.find((item) => item.code === subCounty);
}

export function findWard(hierarchy: KenyaHierarchy | null, code: string | undefined) {
  if (!code) return undefined;
  return findSubCounty(hierarchy, code)?.wards.find((item) => item.code === code);
}

export function resolveLocation(
  hierarchy: KenyaHierarchy | null,
  selection: LocationSelection
): ResolvedLocation {
  return {
    level: levelOf(selection),
    county: findCounty(hierarchy, selection.countyCode),
    subCounty: findSubCounty(hierarchy, selection.subCountyCode),
    ward: findWard(hierarchy, selection.wardCode)
  };
}

/** Breadcrumb trail from Kenya down to the deepest selected level. */
export function locationTrail(location: ResolvedLocation) {
  const trail: Array<{ level: LocationLevel; label: string; code?: string }> = [
    { level: "kenya", label: "Kenya" }
  ];
  if (location.county) {
    trail.push({ level: "county", label: location.county.name, code: location.county.code });
  }
  if (location.subCounty) {
    trail.push({ level: "sub-county", label: location.subCounty.name, code: location.subCounty.code });
  }
  if (location.ward) {
    trail.push({ level: "ward", label: location.ward.name, code: location.ward.code });
  }
  return trail;
}

/** Human-readable place name for headings and document metadata. */
export function locationLabel(location: ResolvedLocation): string {
  if (location.ward) return `${location.ward.name} Ward`;
  if (location.subCounty) return `${location.subCounty.name} Sub-county`;
  if (location.county) return `${location.county.name} County`;
  return "Kenya";
}

/** Selection implied by clicking a code at a given level, clearing anything below it. */
export function selectionFor(level: LocationLevel, code?: string): LocationSelection {
  if (level === "kenya" || !code) return {};
  if (level === "county") return { countyCode: countyCodeOf(code) };
  if (level === "sub-county") {
    return { countyCode: countyCodeOf(code), subCountyCode: subCountyCodeOf(code) };
  }
  return {
    countyCode: countyCodeOf(code),
    subCountyCode: subCountyCodeOf(code),
    wardCode: code
  };
}

export function selectionsEqual(a: LocationSelection, b: LocationSelection) {
  return a.countyCode === b.countyCode && a.subCountyCode === b.subCountyCode && a.wardCode === b.wardCode;
}

export function countWards(county: CountyRef) {
  return county.subCounties.reduce((sum, subCounty) => sum + subCounty.wards.length, 0);
}

/** Case-insensitive search across every level, used by the map's location search box. */
export function searchLocations(hierarchy: KenyaHierarchy | null, query: string, limit = 8) {
  const term = query.trim().toLowerCase();
  if (!hierarchy || term.length < 2) return [];

  const results: Array<{ level: LocationLevel; code: string; label: string; context: string }> = [];

  for (const county of hierarchy.counties) {
    if (county.name.toLowerCase().includes(term)) {
      results.push({ level: "county", code: county.code, label: county.name, context: "County" });
    }
    for (const subCounty of county.subCounties) {
      if (subCounty.name.toLowerCase().includes(term)) {
        results.push({
          level: "sub-county",
          code: subCounty.code,
          label: subCounty.name,
          context: `Sub-county · ${county.name}`
        });
      }
      for (const ward of subCounty.wards) {
        if (ward.name.toLowerCase().includes(term)) {
          results.push({
            level: "ward",
            code: ward.code,
            label: ward.name,
            context: `Ward · ${subCounty.name}, ${county.name}`
          });
        }
      }
    }
  }

  // Exact-prefix matches first so typing "Nairobi" does not rank a ward above the county.
  return results
    .sort((a, b) => {
      const aStarts = a.label.toLowerCase().startsWith(term) ? 0 : 1;
      const bStarts = b.label.toLowerCase().startsWith(term) ? 0 : 1;
      if (aStarts !== bStarts) return aStarts - bStarts;
      return a.label.length - b.label.length;
    })
    .slice(0, limit);
}
